version: '3'
services:
  logic-server:
    container_name: sunburn-recommendations-backend
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - sql-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sunburn-recommendations-sql:3306/sunburnrecommendations
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    networks:
      - sunburn
  sql-server:
      container_name: sunburn-recommendations-sql
      image: mysql:8.0
      ports:
        - "3307:3306"
      environment:
        - MYSQL_PASSWORD=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=sunburnrecommendations
      networks:
        - sunburn
networks:
  sunburn:
    driver: bridge